### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by pastushenkofx** [avored/laravel-ecommerce#170] opened 2018-06-25 15:37 UTC
after installation in main pèage error:

Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Declaration of AvoRed\Framework\Models\Repository\ConfigurationRepository::create($data) must be compatible with AvoRed\Framework\Models\Contracts\ConfigurationInterface::create(array $data)
--------------------------------------------------
<?php
 
namespace AvoRed\Framework\Models\Repository;
 
use AvoRed\Framework\Models\Contracts\ConfigurationInterface;
use AvoRed\Framework\Models\Database\Configuration;
 
class ConfigurationRepository implements ConfigurationInterface
{
    /**
     * Find an Configuration by  given Id
     *
     * @param $id
     * @return \AvoRed\Framework\Models\Database\Configuration
     */
    public function find($id)
    {
        return Configuration::find($id);
    }
 
    /**
     * Find an Configuration by  given Id
     *
     * @param $id
     * @return \AvoRed\Framework\Models\Database\Configuration

---------------------------------------------------------------------------
Declaration of AvoRed\Framework\Models\Repository\ConfigurationRepository::create($data) must be compatible with AvoRed\Framework\Models\Contracts\ConfigurationInterface::create(array $data)

**Comment by GaneshKandu** [comment] 2018-06-26 07:21
Hi

Getting same error

Symfony\Component\Debug\Exception\FatalErrorException thrown with message "Declaration of AvoRed\Framework\Models\Repository\ConfigurationRepository::create($data) must be compatible with AvoRed\Framework\Models\Contracts\ConfigurationInterface::create(array $data)"

laravel.log -> [Uploading laravel.log…]()

system environment

PHP: 7.1.18
MySQL: 5.5.53

**Comment by GaneshKandu** [comment] 2018-06-26 07:21
[laravel.log](https://github.com/avored/laravel-ecommerce/files/2135968/laravel.log)

**Comment by indpurvesh** [comment] 2018-06-26 07:33
does it happen after installation is finished and you visit a home page? or during an installation process?

**Comment by GaneshKandu** [comment] 2018-06-26 07:38
yes

**Comment by GaneshKandu** [comment] 2018-06-26 07:39
after installation is finished and visit a home page

**Comment by indpurvesh** [comment] 2018-06-26 08:37
Thanks I will debug and fix it soon thanks for the bug

**Comment by pastushenkofx** [comment] 2018-06-26 09:22
and not only home

**Comment by pastushenkofx** [comment] 2018-06-26 13:12
And now where should I look?

**Comment by indpurvesh** [comment] 2018-06-26 21:54
I have tried a fresh installation on my computer but still, I can't replicate the bug. But still, I had a commit which I hope to fixed the bug.
Do @pastushenkofx  or @GaneshKandu want to do a `composer update` i hope it helps you to fix the bug

    composer update

**Comment by GaneshKandu** [comment] 2018-06-27 04:02
@pastushenkofx  sorry! but still getting error

[laravel.log](https://github.com/avored/laravel-ecommerce/files/2139723/laravel.log)

**Comment by GaneshKandu** [comment] 2018-06-27 04:04
@indpurvesh  sorry! but still getting error
[laravel.log](https://github.com/avored/laravel-ecommerce/files/2139723/laravel.log)

@pastushenkofx  is your issue get fixed by ```composer update``` ?

**Comment by indpurvesh** [comment] 2018-06-27 04:30
I am not sure for 100% certain because I never able to replicate the bug even on my fresh install.

So you want to open a file ‘vendor/avored/framework/src/Models/Contracts/ConfigurationContract.php@create’ remove array in front of $data so replace the code like 

    Public function create($data);

Let me know if it fixed the bug or not?

**Comment by GaneshKandu** [comment] 2018-06-27 04:37
@indpurvesh its all ready same
```php
    /**
     * Create an Configuration
     *
     * @param array $data
     * @return \AvoRed\Framework\Models\Database\Configuration
     */
    public function create($data);
```

**Comment by indpurvesh** [comment] 2018-06-27 05:06
do you want to put both file code here? 
 - `vendor/avored/framework/src/Models/Contracts/ConfigurationInterface.php`
 - `vendor/avored/framework/src/Models/Repository/ConfigurationRepository.php`

**Comment by GaneshKandu** [comment] 2018-06-27 05:11
[ConfigurationInterface.php.txt](https://github.com/avored/laravel-ecommerce/files/2139832/ConfigurationInterface.php.txt)
[ConfigurationRepository.php.txt](https://github.com/avored/laravel-ecommerce/files/2139833/ConfigurationRepository.php.txt)

**Comment by indpurvesh** [comment] 2018-06-27 05:11
@GaneshKandu Do you want to do a fresh installation? it might fix the bug.


    composer create-project --prefer-dist avored/laravel-ecommerce folder_name
    
Update yours.env file

    cd folder_name
    php artisan avored:install
    php artisan avored:admin:make

**Comment by GaneshKandu** [comment] 2018-06-27 05:29
after ```composer create-project --prefer-dist avored/laravel-ecommerce folder_name```
getting this on ```php artisan avored:install``` command
![untitled](https://user-images.githubusercontent.com/12833130/41954456-e686e0ec-79ca-11e8-9f49-c92437c99c19.png)
[php artisan avored%3Ainstall.txt](https://github.com/avored/laravel-ecommerce/files/2139869/php.artisan.avored.3Ainstall.txt)

**Comment by indpurvesh** [comment] 2018-06-27 05:33
I dont know why but your composer is trying to installed avored/ecommerce:1.8 version instead of avored/ecommerce:1.8.1

try: 
     composer clearcache

then execute create-project command

**Comment by GaneshKandu** [comment] 2018-06-27 05:59
@indpurvesh  Done Dhanyawad
but i am installing in sub-directory of webroot
getting 404 error for fonts in subdirectory install

**Comment by indpurvesh** [comment] 2018-06-27 06:02
to fixed that issue you have to create a virtual-host file if you using an apache. 

One very simple solution is use in build php server

    cd folder_you_have_installed_avored
    php artisan serve

**Comment by GaneshKandu** [comment] 2018-06-27 06:09
The web server artisan uses is the PHP built-in web server, which is not for use in any scenario other than development as showcased by this excerpt from the Built-in web server documentation:

In production you should be using a fully featured web server such as nginx, Apache, lighttpd, etc.

[https://stackoverflow.com/questions/34978857/laravel-how-to-start-server-in-production](https://stackoverflow.com/questions/34978857/laravel-how-to-start-server-in-production)

**Comment by indpurvesh** [comment] 2018-06-27 06:12
Yes, you right.
are you trying to host a website using your own laptop/computer? If you just developing a site only then its a simple and perfectly ok to use PHP in the build server

**Comment by GaneshKandu** [comment] 2018-06-27 06:17
i want it for my production server

**Comment by pastushenkofx** [comment] 2018-06-27 08:41
Ok, perfect, now everything works except categories and /admin/category 

LOG:
[2018-06-27 08:37:00] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at /var/www/rshop/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:181)
[stacktrace]
#0 /var/www/rshop/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(115): Illuminate\\Log\\LogManager->resolve(NULL)
#1 /var/www/rshop/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(103): Illuminate\\Log\\LogManager->get(NULL)
#2 /var/www/rshop/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(526): Illuminate\\Log\\LogManager->driver()
#3 /var/www/rshop/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(113): Illuminate\\Log\\LogManager->error('Declaration of ...', Array)
#4 /var/www/rshop/app/Exceptions/Handler.php(39): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))
#5 /var/www/rshop/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(81): App\\Exceptions\\Handler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))
#6 /var/www/rshop/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))
#7 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()
#8 {main}
"} 
[2018-06-27 08:37:00] laravel.ERROR: Declaration of AvoRed\Framework\Models\Repository\CategoryRepository::create($data) must be compatible with AvoRed\Framework\Models\Contracts\CategoryInterface::create(array $data) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 64): Declaration of AvoRed\\Framework\\Models\\Repository\\CategoryRepository::create($data) must be compatible with AvoRed\\Framework\\Models\\Contracts\\CategoryInterface::create(array $data) at /var/www/rshop/vendor/avored/framework/src/Models/Repository/CategoryRepository.php:8)
[stacktrace]
#0 {main}
"}

**Comment by martinbukowski** [comment] 2018-06-29 00:53
I had this issue.  This issue is due to an interface mismatch.  The interface class (ProductDownloadableUrlInterface) does not type $data as an array, while the implementation (ProductDownloadableUrlRepository) types $data as an array for the create function.

**Comment by indpurvesh** [comment] 2018-06-29 01:00
@martinbukowski I know that I had fixed it. 
But for some reason, I was not getting the bug in my copy.

**Comment by GaneshKandu** [comment] 2018-06-29 10:43
@indpurvesh just tried a install fresh installation of latest avored
Got this error
[php artisan avored%3Ainstall.txt](https://github.com/avored/laravel-ecommerce/files/2148994/php.artisan.avored.3Ainstall.txt)
```sh
composer clearcache
composer create-project --prefer-dist avored/laravel-ecommerce avored
cd avored
#edited .env with my db details
php artisan avored:install
```

**Comment by indpurvesh** [comment] 2018-06-29 19:36
@nteej I have fixed that one but nevermind thanks for the fix,

**Closed by indpurvesh** 2018-06-29 19:36 UTC
Labels: bug

**Comment by carlosmirandazurilla** [comment] 2019-04-20 23:02
I am trying to install Avored and keep on getting this error when on the last step: 

carlos.zurilla@MOBILITY_635 c:\xampp\htdocs\AvoredEcommerce\laravel-ecommerce
# php artisan avored:install

 Do you want to Install Dummy Data? (y/n) [yes]:
 > y

Application key set successfully.
Migration table created successfully.
Migrating: 2017_03_29_000000_avored_framework_schema

Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `created_at` timestamp null, `updated_at` timestamp null) default cha' at line 1 (SQL: create table `avored_order_product` (`id` int unsigned not null auto_increment primary key, `product_id` int unsigned not null, `order_id` int unsigned not null, `qty` int not null, `price` decimal(11, 6) not null, `tax_amount` decimal(11, 6) not null, `product_info` json null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci' engine = InnoDB)

  at C:\xampp\htdocs\AvoredEcommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Database\Connection.php: 664
  660:         // If an exception occurs when attempting to run a query, we'll format the error
  661:         // message to include the bindings with SQL, which will make this exception a
  662:         // lot more helpful to the developer instead of just the database's errors.
  663:         catch (Exception $e) {
  664:             throw new QueryException(
  665:                 $query, $this->prepareBindings($bindings), $e
  666:             );
  667:         }
  668:
  669:         return $result;

  Exception trace:

  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `created_at` timestamp null, `updated_at` timestamp null) default cha' at line 1")
      C:\xampp\htdocs\AvoredEcommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Database\Connection.php : 452

  2   PDO::prepare("create table `avored_order_product` (`id` int unsigned not null auto_increment primary key, `product_id` int unsigned not null, `order_id` int unsigned not null, `qty` int not null, `price` decimal(11, 6) not null, `tax_amount` decimal(11, 6) not null, `product_info` json null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci' engine = InnoDB")
      C:\xampp\htdocs\AvoredEcommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Database\Connection.php : 452

  Please use the argument -v to see more details.

Can someone help?

**Comment by indpurvesh** [comment] 2019-04-21 02:40
This is not a bug. Problem is you are using an mariadb as your database and mariadb don't support json as a database `field`.

Open a file which at: `vendor/avored/framework/database/migrations/2017_03_29_000000_avored_framework_schema.php`

Find the belog code and replace:

    Schema::create('order_product', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('product_id')->unsigned();
            $table->integer('order_id')->unsigned();
            $table->integer('qty');
            $table->decimal('price', 11, 6);
            $table->decimal('tax_amount', 11, 6);
            $table->text('product_info')->nullable()->default(null); // UPDATED LINE
            $table->timestamps();

            $table->foreign('order_id')->references('id')->on('orders');
            $table->foreign('product_id')->references('id')->on('products')->onDelete('cascade');
        });

**Comment by carlosmirandazurilla** [comment] 2019-04-29 17:42
Thanks! Got it to work!
